apiVersion: apps/v1  # ✅ REQUIRED: Defines the API version
kind: Deployment  # ✅ REQUIRED: Defines this as a Deployment
metadata:
  name: bigbank-api
  labels:
    app: bigbank-api
spec:
  replicas: 2  # Change this to increase/decrease pod replicas
  selector:
    matchLabels:
      app: bigbank-api
  template:
    metadata:
      labels:
        app: bigbank-api
    spec:
      containers:
      - name: bigbank-api
        image: bigbankcontainer.azurecr.io/my-fullstack-app:latest  # ✅ Ensure this is your correct image path
        ports:
        - containerPort: 3000  # ✅ Ensure this matches your service.yaml targetPort
        env:
        - name: NODE_ENV
          value: "production"