name: CI/CD for BigBank App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: bigbankcontainer.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build Docker image
        run: docker build -t bigbankcontainer.azurecr.io/bigbank-backend:v14 .
      - name: Push Docker image to ACR
        run: docker push bigbankcontainer.azurecr.io/bigbank-backend:v14
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bigbank-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
