jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_USERNAME }}
        client-secret: ${{ secrets.AZURE_PASSWORD }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: https://bigbankcontainer.azurecr.io/
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        push: true
        tags: bigbankcontainer.azurecr.io/bigbank-backend:${{ github.sha }}
        file: ./backend/Dockerfile