name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure using Managed Identity
        run: |
          az login --identity

      - name: Deploy to Azure Function App
        run: |
          zip -r app.zip .  # Package the app
          az functionapp deployment source config-zip \
            --resource-group BigBankResourceGroup \
            --name BigBankFunctionApp \
            --src app.zip