name: Deploy to Azure Function App

on:
  push:
    branches:
      - main  # Deploy when code is pushed to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

      - name: Deploy to Azure Function App
        run: |
          zip -r app.zip .  # Package the app
          az functionapp deployment source config-zip \
            --resource-group BigBankResourceGroup \
            --name BigBankFunctionApp \
            --src app.zip