name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure CLI
      run: |
        az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bigbankcontainer.azurecr.io/my-fullstack-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f kubernetes/