# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bigbank-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bigbankcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_74ecfcd424ac47a885c53a7ae099a714 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f5d960369914f859da542eac6f4b702 }}

   - name: Build and push container image to registry
  uses: docker/build-push-action@v3
  with:
    context: ./backend  # Use the backend directory as the build context
    push: true
    tags: bigbankcontainer.azurecr.io/bigbank-backend:${{ github.sha }}  # Use the commit hash for versioning
    file: ./backend/Dockerfile  # Specify the Dockerfile location inside the backend directory
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bigbank-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_49225d8e27ee42699841696010b9e3b9 }}
        images: 'bigbankcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_74ecfcd424ac47a885c53a7ae099a714 }}/bigbank-backend:${{ github.sha }}'
